### ISSUE TITLE
Merge crud to master

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/content-loader#2]
Here is a brief example https://github.com/dictyBase/content-loader/tree/feature/crud and it should be self-explanatory. It includes the following...

- All `CRUD` operations
- Uses `fetch` on server side.
- Uses `async and await`.
- Uses modularized version of `yarg` command line parser.
- Use of `moment` module for parsing date.

**Comment by cybersiddhu** [comment]
Merge this branch to master through develop. Create develop, merge this to develop and then merge/rebase to master.

cc @wildlifehexagon

**Comment by wildlifehexagon** [comment]
Merged, also updated README to reflect the new commands
